# -*- coding: utf-8 -*-
"""PS IV exp 10

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iryesgfe9t9TJGwa5BcqtYsBvobRAGia
"""

import pandas as pd 

data = pd.read_csv('titanic.csv')

data.head()

data.embarked

ports = pd.get_dummies(data.embarked , prefix='Embarked')
ports.head()

data = data.join(ports)
data.drop(['embarked'], axis=1, inplace=True)

data.sex = data.sex.map({'male':0, 'female':1})

data.survived.fillna(data.survived.median() ,inplace=True)

y = data.survived.copy()

X = data.drop(['survived'],axis = 1 )

X.drop(['cabin'], axis=1, inplace=True) 
X.drop(['ticket'], axis=1, inplace=True) 
X.drop(['name'], axis=1, inplace=True) 
X.drop(['home.dest'],axis=1, inplace=True)
X.drop(['boat'],axis=1, inplace=True)
X.drop(['body'],axis=1, inplace=True)

X.isnull().values.any()

X.age.fillna(X.age.mean(), inplace=True)
X.pclass.fillna(X.pclass.median(), inplace=True)
X.sex.fillna(X.sex.median(), inplace=True)
X.parch.fillna(X.parch.median(), inplace=True)
X.fare.fillna(X.fare.mean(), inplace=True)
X.sibsp.fillna(X.sibsp.median(), inplace=True)

X.isnull().sum()

X.head()

y.isnull().sum()

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

X_train,X_valid,y_train,y_valid = train_test_split(X,y,test_size = 0.6 , random_state= 16)

pipeline = Pipeline([
    ('scaler',StandardScaler()),
    ('logistic_regression ', LogisticRegression())
])

pipeline.fit(X_train,y_train)

y_pred = pipeline.predict(X_valid)

from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_valid,y_pred)
print(f'accuracy = {accuracy}')

pred_data = pd.DataFrame({'Actual Value':y_valid,'Predicted Value':y_pred,'Difference':y_valid - y_pred})
pred_data

